
const actionTypes = {
    GET_HOME: "GET_HOME",
    SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
    PLAY: "PLAY",
    RANDOM: "RANDOM",
    CHECKVIP: "CHECKVIP",
    LOAD: 'LOAD',
    STATUS_SIDEBAR_RIGHT: "STATUS_SIDEBAR_RIGHT",
    SET_CUR_PLAYLIST_ID: "SET_CUR_PLAYLIST_ID",
    SET_CHANGE_PLAYLIST: "SET_CHANGE_PLAYLIST",
}

export default actionTypes