
const actionTypes = {
    GET_HOME: "GET_HOME",
    SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
    PLAY: "PLAY",
    RANDOM: "RANDOM",
    CHECKVIP: "CHECKVIP",
    LOAD: 'LOAD',
    STATUS_SIDEBAR_RIGHT: "STATUS_SIDEBAR_RIGHT",
    SET_CUR_PLAYLIST_ID: "SET_CUR_PLAYLIST_ID",
    SET_CHANGE_PLAYLIST: "SET_CHANGE_PLAYLIST",
    SET_RECENT_PLAYLIST: "SET_RECENT_PLAYLIST",
    SET_DATA_SEARCH: "SET_DATA_SEARCH",
    SET_SEARCH_SONG: "SET_SEARCH_SONG",
    SET_SEARCH_PLAYLIST: "SET_SEARCH_PLAYLIST",
    GET_ZINGCHART: "GET_ZINGCHART",
    SET_DATA_TOP100: "SET_DATA_TOP100",
    SET_HISTORY_ALBUMS: "SET_HISTORY_ALBUMS",
}

export default actionTypes